dt:
  pre: org.springframework.cloud.devtools:spring-cloud-devtools-
  ver: 1.1.0.BUILD-SNAPSHOT
spring:
  cloud:
    devtools:
      to-deploy:
        - name: configserver
          coordinates: ${dt.pre}configserver:${dt.ver}
          port: 8888
          waitUntilStarted: true
          order: -100
        - name: eureka
          coordinates: ${dt.pre}eureka:${dt.ver}
          port: 8761
        - name: hystrixdashboard
          coordinates: ${dt.pre}hystrixdashboard:${dt.ver}
          port: 7979