info:
  description: Spring Cloud Devtools

eureka:
  client:
    instance-info-replication-interval-seconds: 5
    initial-instance-info-replication-interval-seconds: 5
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

endpoints:
  restart: enabled

ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 60000