server:
  port: 9393

eureka:
  instance:
    status-page-url-path: /admin-ui #allows you to click on the link in eureka dashboard

info:
  artifactId: @project.artifactId@
  description: @project.description@
  version: @project.version@

security:
  basic:
    enabled: false

management:
  context-path: /admin
  security:
    enabled: false